### ISSUE TITLE
Respect `$XDG_CACHE_HOME` for the DB

### ISSUE THREAD

**Issue by MultisampledNight** [mgax/minivirt#9]
On Linux, it's common to follow the [XDG base directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which specifies

> `$XDG_CACHE_HOME` defines the base directory relative to which user-specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used.

Which should change the fallback at

https://github.com/mgax/minivirt/blob/2e6e5f47a0d1a674bbb0ac4bef1b5112614e77f0/minivirt/cli.py#L21

to query `$XDG_CACHE_HOME` and fall back to the original then.

On macOS there's probably something similar, though I'm not really aware of the specs and ecosystem around there.

On a related note, I'm not sure if the cache folder is the best location for the DB. It _does_ contain essential data, so `$XDG_DATA_HOME` might fit better (breaking change).

**Comment by mgax** [comment]
Yep, totally agree! The current state of things comes from "let's have something that functions, clean it up later".
